### ISSUE TITLE
Audit status of existing Congressional district layers by state.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/Beta-Documentation#25]
The goal is to have a single StoryLayer that depicts the changing Congressional district boundaries for all 50 states over time.

First step is to take a data inventory. Please help with filling out this spreadsheet:
https://docs.google.com/spreadsheets/d/14wyMxFg-9WyT7MU5pC0QP1rpA0jDPqNYMLwQe0iLQXY/edit?usp=sharing

**Comment by lhcramer** [comment]
The previous work (done by Everett) from Decision Theater can be found at: 
//Dropbox/MapStory DT Archives/ShapeFiles/Congressional Districts

For Dropbox Account Info contact @jonpmarino

**Comment by nittyjee** [comment]
So how do I access this?
//Dropbox/MapStory DT Archives/ShapeFiles/Congressional Districts

I'll fill it all out when I can get a hold of it.

**Comment by lhcramer** [comment]
If you log into dropbox (either client or web) that is the path to the congressional district directory. `//Dropbox` is to represent wherever your dropbox folder is located. Jon has the log in info for the dropbox account

**Comment by nittyjee** [comment]
Jon - can you send us the login info?
Or anyone who has it?

thanks

**Comment by nittyjee** [comment]
Okay, got access from Jon, downloading now... several files are around 1-2 gigs... it'll take a few hours to download. If anyone knows what's in these files, or have their own data, go ahead and feel free to fill out the form.

**Comment by nittyjee** [comment]
Jon - hope it's okay I switched to a google doc spreadsheet - i find the github markdown a bit too... markdowny. If you disagree, feel free to revert.

**Comment by lhcramer** [comment]
Resolution:   
- Obtained Geometry of Congressional Districts from original source used by Everett which is the same base data Karl is updating. 
- Script to Import into PostGIS and then segment national shapefiles into states created. 

Next Steps (See Issues):  
- #29 
- #30 
- #32 
- #35
